Np 1555 start registration
BIBSYSDEV/NVA-Frontend pull request #1060
Opened 2020-09-28 10:42 UTC by elkebab

2020-09-28 10:43 UTC, elkebab commented on src/pages/publication/EditPublication.tsx
kan fjerne en del her siden vi ikke trenger infoboksen lenger

2020-09-28 11:08 UTC, sarahse submitted a review, later dismissed

2020-09-28 15:06 UTC, sarahse commented on src/translations/en/publication.json
> +    "start_with_link_to_resource": "Link to original version if the resource already have been published on the Internet",
```suggestion
    "start_with_link_to_resource": "Link to original version if the resource already has been published on the Internet",
```

2020-09-28 15:06 UTC, sarahse commented on src/translations/en/publication.json
> +    "start_with_uploading_file": "Upload file if the resource is to be published om the Internet for the first time"
```suggestion
    "start_with_uploading_file": "Upload file if the resource is to be published on the Internet for the first time"
```

2020-09-28 15:07 UTC, sarahse requested changes
typos

2020-09-29 07:29 UTC, sarahse approved these changes

2020-09-29 07:32 UTC, merged