Np 2316 resource tab
BIBSYSDEV/NVA-Frontend pull request #1581
Opened 2021-03-10 16:51 UTC by elkebab

Rename reference tab til resource type
(følg med på oversettelser fremover 😬) 

TODO: oppdater scenario (https://github.com/BIBSYSDEV/NVA-scenarios/pull/128)

2021-03-11 09:03 UTC, sarahse commented on src/utils/formik-helpers.ts
>        return {
Nå skal jeg være streng og ikke godkjenne denne før scenarioene er endret i NVA-scenarios :) :) :)

2021-03-11 09:03 UTC, sarahse requested changes
Scenario først

2021-03-12 06:52 UTC, Eiriknil approved these changes

2021-03-15 08:27 UTC, sarahse approved these changes

2021-03-15 09:19 UTC, merged