NP-45010 updated display of ticket age
BIBSYSDEV/NVA-Frontend pull request #4293
Opened 2023-07-11 07:58 UTC by iBuzza

2023-07-11 11:37 UTC, truhacevkir approved these changes

2023-07-12 10:19 UTC, ketilaa approved these changes

2023-07-12 10:19 UTC, ketilaa commented on src/pages/messages/components/TicketListItem.tsx
> +  const getTodayDateString = () => {
Don't you have a date library available in you project to format dates?

2023-07-14 06:44 UTC, Eiriknil approved these changes

2023-07-23 15:42 UTC, elkebab commented on src/pages/messages/components/TicketListItem.tsx
> +  const getTodayDateString = () => {
Trengs strengverdien til nå-dato til noe? Ser ut som et unødvendig ekstra steg med mye kompleksitet nå. Hva med å bare opprette nå-dato direkte i `getTimePeriodString()` i stedet? Ser ut som den bare trenger å ta inn en dato som argument, og så kan den finne differansen mellom input-dato og nå-dato (som den kan lage selv)

2023-07-23 15:45 UTC, elkebab commented on src/utils/general-helpers.ts
> +    return t('common.x_days', { count: daysDiff });
Har noen kommet med ønske at vi skal ha oppløsning på mer enn døgn her? Min oppfatning fra skisser og prat med PO var at antall dager var minste enhet som skulle vises
```suggestion
  if (daysDiff < 30) {
    return t('common.x_days', { count: daysDiff });
```

2023-07-23 15:48 UTC, elkebab commented on src/pages/messages/components/TicketListItem.tsx
> +  const getTodayDateString = () => {
Side note: Om vi har behov for strengversjonen (ISO) av en dato burde `new Date().toISOString()` brukes, både for å unngå egne bugs og forå beholde info om tidssone etc

2023-07-23 15:52 UTC, elkebab requested changes

2023-07-23 15:52 UTC, elkebab commented on src/pages/messages/components/TicketListItem.tsx
> +  const getTodayDateString = () => {
Trengs strengverdien til nå-dato til noe? Ser ut som et unødvendig ekstra steg med mye kompleksitet nå. Hva med å bare opprette nå-dato direkte i getTimePeriodString() i stedet? Ser ut som den bare trenger å ta inn en dato som argument, og så kan den finne differansen mellom input-dato og nå-dato (som den kan lage selv)

Også: Om vi har behov for strengversjonen (ISO) av en dato burde new Date().toISOString() brukes, både for å unngå egne bugs, og for å beholde info om tidssone etc

2023-07-23 15:52 UTC, elkebab commented on src/utils/general-helpers.ts
> +  } else if (daysDiff < 30) {
Har noen kommet med ønske at vi skal ha oppløsning på mer enn døgn her? Min oppfatning fra skisser og prat med PO var at antall dager var minste enhet som skulle vises
```suggestion
  if (daysDiff < 30) {
```

2023-08-08 10:41 UTC, closed without merging