Np 44828 update inst conf rbo
BIBSYSDEV/NVA-Frontend pull request #4662
Opened 2023-10-20 06:32 UTC by siricv

2023-10-20 07:41 UTC, iBuzza commented on src/pages/basic_data/app_admin/CustomerInstitutionMetadataForm.tsx
> +                    }}>
Ser i skissene at det er brukt bold font på nvi og rbo, så lan være greit å legge inn dette på alle `FormLabel` det gjelder.
```suggestion
                  <FormLabel
                    component="legend"
                    sx={{
                    fontWeight: 'bold',
                      marginTop: '-1rem',
                      marginLeft: '2rem',
                    }}>
```

2023-10-20 11:41 UTC, iBuzza approved these changes

2023-10-24 14:47 UTC, elkebab commented on src/pages/basic_data/app_admin/CustomerInstitutionMetadataForm.tsx
> +                      marginTop: '-1rem',
Negative verdier for margin og padding er ting man helst vil unngå, da det som regel er lagt in for å fjerne effekten av noe annet. Da er det bedre å fjerne rotårsaken, da det gir enklere kode heller enn å ha to motstridende effekter.
I tilfellet her kan du fjerne `marginTop`:
```suggestion
```
og wrappe dette i en ny div:
```
<div>
  <Field name={CustomerInstitutionFieldNames.NviInstitution}>
      (...)
   </Field>
   <Field name={CustomerInstitutionFieldNames.RboInstitution}>
      (...)
   </Field>
</div>
```
Da kan vi fjerne erstatte begge `<div>`  som ligger inn `<Field>` med `<>`  også

2023-10-24 14:59 UTC, elkebab commented on src/pages/editor/EditorInstitution.tsx
disabled felter betyr vanligvis at de kan endres, bare ikke med current state, ev. at man mangler tilganger til det. 
Tenker det gir mening å vise dette som rene tekster i stedet for checkboxer, som jeg ser er gjort i skissene også. 
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/4c5213fb-947e-40e2-a14b-af585f477c6e)

2023-10-24 15:07 UTC, elkebab commented on src/pages/basic_data/app_admin/CustomerInstitutionMetadataForm.tsx
>                      control={
For å sikre at RBO nullstilles (settes til `false`) når man nullstiller NVI:
```
<Checkbox
  data-testid={dataTestId.basicData.institutionAdmin.nviInstitutionCheckbox}
  {...field}
  checked={field.value}
  onChange={(event, checked) => {
    if (!checked) {
      setFieldValue(CustomerInstitutionFieldNames.RboInstitution, false);
    }
    field.onChange(event);
  }}
/>
```

2023-10-24 15:08 UTC, elkebab requested changes
Noen små forslag til forbedringer. Si fra om noe ikke er helt klart!

2023-10-30 11:42 UTC, elkebab commented on src/pages/basic_data/app_admin/CustomerInstitutionMetadataForm.tsx
> +                  </>
Her kan vi også forenkle litt, ved å oppgi innrykk en plass i stedet for to. Stor fordel når sånne ting skal endres senere at det ligger bare en plass, for å unngå at de kommer ut av sync.


```suggestion
                  <Box sx={{ ml: '2rem' }}>
                    <FormLabel
                      component="legend"
                      sx={{ fontWeight: 'bold' }}>
                      {t('common.rbo')}
                    </FormLabel>
                    <FormControlLabel
                      label={t('basic_data.institutions.institution_receives_funding_via_rbo')}
                      disabled={!values.customer.nviInstitution}
                      control={
                        <Checkbox
                          data-testid={dataTestId.basicData.institutionAdmin.rboInstitutionCheckbox}
                          {...field}
                          checked={field.value}
                        />
                      }
                    />
                  </Box>
```

2023-10-30 12:22 UTC, elkebab approved these changes

2023-10-30 12:24 UTC, merged