Np 45448 tableau reports
BIBSYSDEV/NVA-Frontend pull request #4673
Opened 2023-10-21 21:25 UTC by iBuzza

2023-10-24 08:30 UTC, anetteOlli approved these changes

2023-10-24 08:30 UTC, anetteOlli commented on src/pages/search/registration_search/ReportsPage.tsx
> +        src="https://rapport-dv.uhad.no/t/DUCT/views/nettsider_2022_14_04_v2/NVI2011-2022?%3Aembed=y&%3AloadOrderID=0&%3Adisplay_spinner=yes&%3AshowAppBanner=false&%3Atoolbar=yes&%3Atabs=no"
constant?

2023-10-24 15:20 UTC, elkebab requested changes

2023-10-24 15:20 UTC, elkebab commented on src/pages/search/SearchPage.tsx
Skal vi ta inn dette må vi nok minimere filtrene til venstre også. Nå kan jeg velge nye filter _etter_ jeg har valgt "Rapporter" uten at det har noen betydning. Det er heller ikke åpenbart for meg at man kommer seg tilbake til søket ved å trykke på "Rapporter" igjen ( at det i ppraksis er en toggle).

![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/69b15537-a8e0-4d10-abc6-fa5493212e2d)

Ser ut på skissene at dette skal være likt som på andre sider, at alt får en accordion som utvides når den er valgt:
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/ea43123c-3f7f-4cef-b5cc-0d48f4e04a88)

2023-10-24 15:21 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +        id="inlineFrameExample"
copy-paste-glipp her også?

2023-10-24 15:21 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +        title="NVI"
i18n

2023-10-24 15:26 UTC, elkebab commented on src/pages/search/SearchPage.tsx
ville vurdert en egen PR som order menyoppsettet først

2023-10-27 10:16 UTC, iBuzza commented
LItt usikker på hvordan jeg skal løse hele greia med accordions. Blir mye funky states uten konkrete paths, så kanskje greit å bare legge til det?

2023-10-31 11:30 UTC, elkebab commented on src/pages/dashboard/HomePage.tsx
> +                        {t('search.no_available_filters')}
Burde kanskje ikke vise denne mens søket pågår?
Missvisende å vise at det ikke finnes noen søkefilter, før de plutselig dukker opp likevel
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/0cf575af-091a-4224-a871-f9dd08707d8c)

2023-10-31 11:38 UTC, elkebab commented on src/pages/dashboard/HomePage.tsx
> +                  onClick={() => resetForm()}>
Ser ikke ut som resetForm virker helt eller? ser fortsatt bugen hos meg når jeg navigrer mellom filter og rapporter

2023-10-31 11:41 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +    <Box>
Litt margin hadde nok gjort seg på mobil 
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/b0a14903-1582-4446-b8c6-a915092af218)

2023-10-31 11:44 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +      <iframe
kunne nok med fordel vært litt smalere på mobil? litt usikker på hvor fint vi får det når det er iframe, men ser for meg det hadde vært bedre om det ikke hadde vært bredere enn vår side. Selv om det vil bety enda mer horisontal scroll da
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/08002752-5914-4a18-b383-7fa17550160a)

2023-10-31 11:45 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +        id="nvi-report"
brukes denne `id`-en til noe?

2023-10-31 11:49 UTC, elkebab commented on src/resources/images/report-thumbnail.png
Kan kanskje komprimeres litt mer, for å minimere dataoverføring?
Om det ikke trengs å vises noen detaljer i det bilde brukeren ser, så trenger vi ikke overføre et bilde med høyere kvalitet enn det heller

2023-10-31 14:02 UTC, elkebab commented on src/pages/dashboard/HomePage.tsx
> +                  onClick={() => resetForm()}>
For å reprodusere må du åpne siden direkte enten via link eller som refresh, feks: http://localhost:3000/?query=%22kapittel%22+AND+(topLevelOrganization.id%3D%22https%3A%2F%2Fapi.dev.nva.aws.unit.no%2Fcristin%2Forganization%2F20754.0.0.0%22)+AND+(entityDescription.contributors.identity.id%3A%22https%3A%2F%2Fapi.dev.nva.aws.unit.no%2Fcristin%2Fperson%2F1136254%22)&results=10&from=0

Når man da klikker på "Rapporter", og så "Filter" igjen vil filtrene fortsatt være der, men de vil ikke brukes

2023-10-31 14:15 UTC, anetteOlli approved these changes

2023-11-01 11:15 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +    <Box>
Tom `<Box>`?

2023-11-01 11:17 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +    <Box>
Tom `<Box>`?
```suggestion
    <>
```

2023-11-01 11:19 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
> +      <iframe
Sikkert ikke mulig, siden vi må vise hele iframen uansett

2023-11-01 11:20 UTC, elkebab commented on src/pages/dashboard/HomePage.tsx
> +    <>
Unødvendig innrykk
```suggestion
```

2023-11-01 11:20 UTC, elkebab commented on src/pages/dashboard/HomePage.tsx
> +                  <>
```suggestion
```

2023-11-01 11:36 UTC, elkebab commented on src/pages/search/SearchPage.tsx
> +              }
Tidligere resatte vi verdiene når man valgte en type, noen grunn til at det er tatt vekk?

  https://github.com/BIBSYSDEV/NVA-Frontend/blob/1a1bd326f58790a32cd030112ffeadad51c843d2/src/pages/search/SearchPage.tsx#L172

2023-11-01 11:37 UTC, elkebab commented on src/pages/search/SearchPage.tsx
> +              }
På branchen her brukes ikke `emptySearchConfig` lenger, så om bruken er tatt ut me vilje burde den eventuelt fjernes også

2023-11-01 15:17 UTC, iBuzza commented on src/pages/search/registration_search/filters/FacetItem.tsx
> +  const [showAll, setShowAll] = useState(false);
Har ikke funnet noen åpenbare feil ved å endre denne, men må muligens testes litt mer. Er ihvertfall ikke noe breaking.

2023-11-02 08:54 UTC, iBuzza commented on src/pages/search/SearchPage.tsx
> +              }
My bad. Er nok best å beholde den.

2023-11-02 12:29 UTC, elkebab commented on src/pages/search/registration_search/ReportsPage.tsx
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/f5f379c4-dd2d-418a-8722-d113bfccb7ba)

2023-11-02 12:33 UTC, elkebab commented on src/pages/search/registration_search/filters/FacetItem.tsx
> +  const [showAll, setShowAll] = useState(false);
Ser ikke noen åpenbare feil jeg heller, så tenker vi prøver det sånn

2023-11-02 12:56 UTC, elkebab approved these changes

2023-11-02 12:56 UTC, iBuzza commented on src/pages/search/registration_search/ReportsPage.tsx
Glemte at tomt JSX ikke funker som en container

2023-11-02 13:00 UTC, merged