Np 45732 change text when publishing without file
BIBSYSDEV/NVA-Frontend pull request #5022
Opened 2024-01-15 12:42 UTC by iBuzza

2024-01-15 13:27 UTC, elkebab commented on src/pages/messages/components/PublishingRequestMessagesColumn.tsx
>                <Typography>{t('registration.files_and_license.files_awaits_approval_unknown')}</Typography>
skal det fortsatt stå at man venter godkjenning på fil selv om den ikke har filer?

2024-01-16 07:41 UTC, elkebab commented on src/pages/messages/components/PublishingRequestMessagesColumn.tsx
> +            ((ticket.status === 'Pending' || ticket.status === 'New') && registrationHasFiles ? (
```suggestion
            ((ticket.status === 'Pending' || ticket.status === 'New') ? (
```

2024-01-16 07:43 UTC, elkebab commented on src/pages/messages/components/PublishingRequestMessagesColumn.tsx
> +          {registrationHasFiles &&
`registrationHasFiles` baseres bare på allerede publiserte filer nå, så det vil aldri være ikke-publiserte `filer` her (se på hvordan propen settes i `TicketListItem` feks

2024-01-16 14:05 UTC, elkebab requested changes

2024-01-16 14:05 UTC, elkebab commented on src/pages/messages/components/PublishingRequestMessagesColumn.tsx
> +          {registrationHasFiles &&
`registrationHasFiles` baseres bare på allerede publiserte filer nå, så det vil aldri være ikke-publiserte filer her (se på hvordan propen settes i `TicketListItem` feks

2024-01-18 11:39 UTC, anetteOlli submitted a review, later dismissed

2024-01-22 13:38 UTC, iBuzza commented on src/pages/messages/components/PublishingRequestMessagesColumn.tsx
> +          {registrationHasFiles &&
Må ta en manuell gjennomgang, men tor det er i orden nå.

2024-01-23 08:36 UTC, elkebab commented on src/pages/public_registration/action_accordions/PublishingAccordion.tsx
> +          ))}
```suggestion
            <Typography sx={{ mt: '0.5rem' }}>
              {registrationHasFile ? t('registration.public_page.tasks_panel.registration_is_published_with_files') : t('registration.public_page.tasks_panel.registration_is_published')}
            </Typography>
```

2024-01-23 08:40 UTC, elkebab commented on src/pages/public_registration/action_accordions/PublishingAccordion.tsx
> +  const registrationHasFile = registration.associatedArtifacts.some((artifact) => associatedArtifactIsFile(artifact));
1. ønsker vi fortsatt denne nå som dette ligger i ticket? Siden vi ikke har tilgang til registration i oppgave-lista, så vi må uansett bruke tickets der, derfor lurer jeg på om det er lurest å gjøre det her også

2024-01-23 08:42 UTC, elkebab commented on src/pages/messages/components/TicketListItem.tsx
> +            />
Trenger ikke å regne ut `registrationHasFiles` i denne komponenten når sender med all data som trengs for å finne det ut uansett. Bedre å finne begrense data til der det trengs
```suggestion
            <PublishingRequestMessagesColumn
              ticket={ticket as ExpandedPublishingTicket}
            />
```

2024-01-23 08:44 UTC, elkebab commented
NB! Dette avhenger av https://unit.atlassian.net/browse/NP-46031, som helst bør være i prod før merge

2024-01-23 09:58 UTC, iBuzza commented on src/pages/public_registration/action_accordions/PublishingAccordion.tsx
> +  const registrationHasFile = registration.associatedArtifacts.some((artifact) => associatedArtifactIsFile(artifact));
`approvedFiles` og `filesForApproval` ligger kun på `ExpandedPublishingTicket`, pg her sendes det inn `PublishingTicket`.

2024-01-23 11:52 UTC, elkebab commented on src/pages/public_registration/action_accordions/PublishingAccordion.tsx
> +  const registrationHasFile = registration.associatedArtifacts.some((artifact) => associatedArtifactIsFile(artifact));
er det ikke egentlig denne du er interessert i? om brukeren nå legger til en ny fil etter å ha fått godkjent en ticket, vil det stå at filer er publisert, selv om det ikke er det (har ikke sjekka i praksis, men frmestår sånn)
```suggestion
  const registrationHasFile = registration.associatedArtifacts.some((artifact) => artifact.type === "PublishedFile");
```

2024-01-23 11:59 UTC, elkebab commented on src/pages/public_registration/action_accordions/PublishingAccordion.tsx
> +  const registrationHasFile = registration.associatedArtifacts.some((artifact) => associatedArtifactIsFile(artifact));
etter litt DM på slack: blir et problem uansett siden vi per i dag bare tar hesnyn til den siste ticketen. Dette blir ikke helt bra før vi løser det. Så blir å finne et fornuftig kompromiss i denne omang

2024-01-23 12:12 UTC, elkebab commented on src/pages/messages/components/PublishingRequestMessagesColumn.tsx
> +            ))}
Blir ikke enig med meg selv for om det er best å basere dette på `ticket.type` eller `approvedFiles`/`filesForApproval` 🤔 
I teorien åpner vi her for å vise "Fil(er) venter på publisering" selv om alle filer er i `approvedFiles`, så det kan jo bli noen spennende bugs om backend feiler i å holde alt i sync en dag. Men for nå tror jeg det er bra nok sånn 👍

2024-01-29 09:40 UTC, elkebab approved these changes
Koden ser bra ut, men har ikke testet så husk å sjekk litt ulike tilfeller før merge :)

2024-01-29 12:54 UTC, merged