NP-46362 Add checkbox to exclude subunits
BIBSYSDEV/NVA-Frontend pull request #5294
Opened 2024-03-05 14:19 UTC by iBuzza

2024-03-06 09:46 UTC, anetteOlli submitted a review, later dismissed

2024-03-06 11:25 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
Er dette noe som virker godt nok til at vi er komfortable med å rulle ut i prod og vise på demo på mandag? 🤔 

![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/027cbebe-7f3f-4caf-8262-de38fb0c8616)
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/9f5b1426-b1c5-456c-a130-cc72d2b6077b)

2024-03-06 11:28 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
Skjer noe rart på mobil her
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/fe3b8cae-641d-4bf5-a6d2-fe612e2f0498)

2024-03-06 11:30 UTC, elkebab commented on src/api/searchApi.ts
> +  [ResultParam.ExcludeSubunits]?: 'true' | null;
Naturlig at dette er `boolean`, på samme måte som det er løst for ticket search?

```suggestion
  [ResultParam.ExcludeSubunits]?: boolean | null;
```

2024-03-06 11:32 UTC, elkebab commented on src/api/searchApi.ts
> +  [ResultParam.ExcludeSubunits]?: 'true' | null;
Da kan det settes som noe sånt for `FetchResultsParams`: `excludeSubunits: Boolean(params.get(ResultParam.ExcludeSubunits))`

2024-03-06 11:34 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +            <FormControlLabel
Ser ut som denne mangler gap, som gjør at checkbox faktisk overlapper select-boxen litt
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/2b7fdb5d-0e25-45e6-abcc-11a60bbdaeec)

2024-03-06 11:35 UTC, elkebab requested changes
div

2024-03-06 14:57 UTC, iBuzza commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
Human error. Skal være i orden nå

2024-03-06 14:57 UTC, iBuzza commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
Hadde klart å fjerne `flexWrap`

2024-03-06 14:58 UTC, iBuzza commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +            <FormControlLabel
økte gap til `1rem`

2024-03-06 15:21 UTC, iBuzza commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
Irriterte meg litt at feltene ikke brukte hele bredden på mobil, så har endret litt på layout. Det medfører at `"Ekskluder underenheter"` kommer på to linjer, men tenker at det ikke er så ille.

2024-03-07 11:57 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +            <FormControlLabel
fortsatt ulik størrelse på gaps her pga 2 flex-bokser. som diskutert kan vi flytte denne inni OrganizationFilters, og ta vekk Box som er parent her, så har vi bare 1 flex som bestemmer layout her

2024-03-07 11:59 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
gir mening å droppe at den blir over to rader imo (for alle skjermstørrelser)

2024-03-07 12:02 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +    excludeSubunits: Boolean(excludeSubunits),
Når "castes" `'true'` til `'true'`, for så å castes til `true`, som egentlig er overflødig.
```suggestion
    excludeSubunits: params.get(ResultParam.ExcludeSubunits) === 'true',
```

2024-03-07 12:05 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +  const excludeSubunits = params.get(ResultParam.ExcludeSubunits) === 'true' ? 'true' : null;
Oppnår ikke noe med å "caste" `'true'` til `'true'`. Bare fint om vi får denne til å bli riktig type raskere

```suggestion
  const excludeSubunits = params.get(ResultParam.ExcludeSubunits) === 'true';
```

2024-03-07 12:06 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +  const excludeSubunits = params.get(ResultParam.ExcludeSubunits) === 'true' ? 'true' : null;
Da kan vi under her ha 
```
excludeSubunits,
topLevelOrganization: excludeSubunits && !!unitId ? null : topLevelOrganizationId,
```

2024-03-07 12:14 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +            <FormControlLabel
Det jeg mener her er at gapsene her burde være like, og at de burde bestemmes av bare en flex-boks:
![bilde](https://github.com/BIBSYSDEV/NVA-Frontend/assets/6313468/b283e865-6043-4f19-a414-ddc9b1e60a8b)

2024-03-11 07:31 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
snakket vi ikke om å droppe wrap på "Ekskluder underenheter"?
Burde holde med en `whiteSpace: 'nowrap'` på `FormControlLabel`, om vi ikke finner en enkel måte der det blir automatisk rett, da det ikke ser ut til å være en åpenbare grunn til å wrappe her 🤔

2024-03-11 13:32 UTC, iBuzza commented
Mellom `1280vw` og `1376vw` blir hele boksen dyttet ned et hakk, og det vises fortsatt en divider. Litt usikker på hvor nøye vi skal være på slike forskjeller.
![Uploading Screenshot 2024-03-11 at 14.32.20.png…]()

2024-03-11 13:41 UTC, elkebab approved these changes

2024-03-11 13:43 UTC, merged