Exclude topLevelOrg from search when subUnnit is selected
BIBSYSDEV/NVA-Frontend pull request #5408
Opened 2024-03-22 11:09 UTC by iBuzza

# Description

Link to Jira issue:

# Checklist

## Required

- [x] The changes are working as expected
- [x] The changes are tested OK for both desktop and mobile screens
- [x] The changes are tested OK for a11y (with [axe](https://www.deque.com/axe/devtools/), [lighthouse](https://developer.chrome.com/docs/lighthouse/), or similar)
- [x] Interactive elements have data-testids
- [x] I have done a QA of my own changes

## Optional

- [ ] Solution is verified by PO/designer

2024-03-22 11:29 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +    topLevelOrganization: (excludeSubunits && !!unitId) || !!unitId ? null : topLevelOrganizationId,
burde ikke denne heller vært i `fetchResults`, sånn at det gjelder overalt?
```
if (params.topLevelOrganization) {
  if (params.unit) {
    searchParams.set(ResultParam.Unit, params.unit);
  } else {
    searchParams.set(ResultParam.TopLevelOrganization, encodeURIComponent(params.topLevelOrganization));
  }
}
```

2024-03-22 11:29 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +    topLevelOrganization: (excludeSubunits && !!unitId) || !!unitId ? null : topLevelOrganizationId,
```suggestion
    topLevelOrganization: topLevelOrganizationId,
```

burde ikke denne heller vært i `fetchResults`, sånn at det gjelder overalt?
```
if (params.topLevelOrganization) {
  if (params.unit) {
    searchParams.set(ResultParam.Unit, params.unit);
  } else {
    searchParams.set(ResultParam.TopLevelOrganization, encodeURIComponent(params.topLevelOrganization));
  }
}
```

2024-03-22 11:57 UTC, iBuzza commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
> +    topLevelOrganization: (excludeSubunits && !!unitId) || !!unitId ? null : topLevelOrganizationId,
Gjorde det litt annerledes, mon tror det skal funke på samme måte. Med mindre det er en case hvor vi faktisk vil ha topLevelOrg og Unit?

2024-03-22 13:53 UTC, elkebab commented on src/api/searchApi.ts
> +    searchParams.delete(ResultParam.TopLevelOrganization);
litt wonky å legge til denne noen linjer over, om vi bare skal fjerne på neste? Ville vurdert å slå sammen til at vi bare setter verdier vi faktisk skal ha, men det funker jo læll da såklart

2024-03-22 13:53 UTC, elkebab approved these changes

2024-03-22 13:58 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
>      unit: unitId,
Tror dette burde være nor sånt, ref diskusjon på slack: 
```suggestion
    unit: unitId || topLevelOrganizationId,
```

2024-03-22 13:59 UTC, elkebab commented on src/pages/search/advanced_search/AdvancedSearchPage.tsx
>      unit: unitId,
i settingen her er vi alltid interessert i unit, aldri topLevelOrg

2024-03-22 14:49 UTC, iBuzza commented
Avventer med denne til vi har kommet frem til en endelig løsning på det

2024-03-25 10:31 UTC, elkebab requested changes
Søk alltid på `unit` fra avansert søk (ikke topLevel)

2024-04-02 13:19 UTC, merged