NP-47087 Changes to Project and Funding
BIBSYSDEV/NVA-Frontend pull request #5975
Opened 2024-07-30 11:47 UTC by iBuzza

# Description

Link to Jira issue: TODO

[TODO: Describe what this PR solves]

# Checklist

Ensure that the changes are aligned with the expectations of PO/designer before marking the PR as ready for review.

Also ensure that the following criterias are met:

- [ ] The changes are working as expected
- [ ] The changes are tested OK for different screen sizes
- [ ] The changes are tested OK for a11y
- [ ] Interactive elements have data-testids
- [ ] I have done a QA of my own changes

_Note: some of these criterias may not always be relevant, and can simply be marked as completed._

2024-08-12 07:56 UTC, elkebab commented on src/translations/nbTranslations.json
> +        "funding_without_project_description": "<0>Mottar forskningen finansiering som ikke er tilknyttet et prosjekt så trykk på \"Legg til ny finansiering\" og deretter søk etter finansiør.</0> <0>
```suggestion
        "funding_without_project_description": "<0>Mottar forskningen finansiering som ikke er tilknyttet et prosjekt så trykk på \"Legg til ny finansiering\" og deretter søk etter finansiør.</0> <0>Ikke registrer finansiering som er tilknyttet et prosjekt. Finansiering tilknyttet prosjekt legges til når du legger til prosjekt lengre opp på siden. Hvis ikke informasjonen om finansiering vises så må dette registreres på prosjektet i NVA.</0>",
```

2024-08-12 08:00 UTC, elkebab commented on src/translations/nbTranslations.json
> +        "funding_without_project_description": "<0>Mottar forskningen finansiering som ikke er tilknyttet et prosjekt så trykk på \"Legg til ny finansiering\" og deretter søk etter finansiør.</0> <0>
Teksten samsvarer ikke med knappen. Dette ble fikset for alle(?) knapper før helga så kanskje en stund siden du har pulla?
![bilde](https://github.com/user-attachments/assets/cb2299e1-db7a-41e1-9c27-f580828527bd)

2024-08-12 08:11 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectsField.tsx
> +        size="small"
Ble en ganske stor knapp
![bilde](https://github.com/user-attachments/assets/2743b4ea-c742-49eb-ba7d-960663643a97)

```suggestion
        sx={{ alignSelf: 'center' }}
```

2024-08-12 08:15 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectsField.tsx
> +const ProjectItem = ({ projectId, removeProject }: ProjectItemProps) => {
stor fil, så kanskje naturlig å legge dette i en egen fil?

2024-08-12 08:32 UTC, elkebab commented on src/types/project.types.ts
> +  funding?: ProjectFunding[];
Ser ikke ut som dette er en del av modellen?
```suggestion
```
![bilde](https://github.com/user-attachments/assets/6d6df03b-fad4-4dc2-8e2d-c2ed9bff5d31)

2024-08-13 10:29 UTC, iBuzza reviewed
Implementer feedback. Er en del conditionals i `ProjectItem`, men tror det er nødvendig for å dekke alle cases.

2024-08-13 13:42 UTC, elkebab requested changes
Ble en del kommentarer, men går stort sett på småting!

2024-08-14 07:52 UTC, iBuzza commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +      <Box sx={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', height: '100%' }}>
Er noe snedig med hvordan disse containerne oppfører seg, så må se litt nærmere på det 🤔

2024-08-14 08:30 UTC, iBuzza commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +            <Box sx={{ display: 'flex', gap: '2rem' }}>
Ja, enig i at det er litt mye. Men fant ingen annen måte å holde de fire undertitlene på relativt samme linje uavhengig av hvor lang tittelen på prosjektet er (om det gir mening)

2024-08-14 08:36 UTC, iBuzza commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +              sx={{ display: 'grid', gridTemplateRows: '1fr 1fr', gap: '1rem', height: '100%' }}>
Trenger height for å holde `koordinerende institusjon` og `tilskudds-ID` på samme linje.

2024-08-14 10:22 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +            <Box sx={{ display: 'flex', gap: '2rem' }}>
I så fall hadde det også vært forenklet med bare en grid, da hvert grid item hadde blitt ett innslag:
```html
<Box sx={{ display: "grid", gridTemplateColumns: { sm: '1fr', md: '1fr 1fr auto' } }}>
  <div>
    <Typography>FINANSIØR</Typography>
    <Typography paragraph>xxxx</Typography>
  </div>
  
  <div>
    // Innhold i rad 1, kolonne 2
  </div>

  <div>
    // Innhold i rad 2, kolonne 1
  </div>

  <div>
    // Innhold i rad 2, kolonne 2
  </div>

   <RemoveProjectButton /> // måtte kanskje satt eksplisitt colonne 3 på denne (og resten)
</Box>
```
Da hadde denne ene griden sikret at alt var på linje

2024-08-14 10:30 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +                    {project?.title}
Fortsatt en overflødig `project?.id` her

2024-08-14 10:34 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +                        sx={{ display: 'flex', gap: '1rem' }}
Her brukes 2 flex-bokser, mens i første kolonne er det bare en flex i selve linken. Ser ut som det er en overflødig div og flex her?

2024-08-14 10:37 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +                        component={Link}
Som vi snakket om tidligere i dag så er `react-router` for å linke internt i vår app, så her holder det med `MuiLink`.
Husk alltid å sjekk at linkene (og annet virker også):
![bilde](https://github.com/user-attachments/assets/4ba20b65-66e2-4cc6-bbc8-ec144de550f5)

```suggestion
```

2024-08-14 14:37 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +    <>
Fjern overflødig tag her, så ser det ut som vi er good!
```suggestion
```

2024-08-14 14:38 UTC, elkebab commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +                {index > 0 && <Divider sx={{ width: '50%' }} />}
har ikke testet, men husk at 50% kan bli rart på mobil igjen. Ikke at akkurat dette er topp-pri på mobil, but still

2024-08-15 05:46 UTC, iBuzza commented on src/pages/registration/description_tab/projects_field/ProjectItem.tsx
> +                {index > 0 && <Divider sx={{ width: '50%' }} />}
Synes ikke det ser så ille ut 🤔 
<img width="548" alt="Screenshot 2024-08-15 at 07 45 30" src="https://github.com/user-attachments/assets/31780d0a-3092-4957-be28-9094b7f0842b">

2024-08-15 06:29 UTC, elkebab approved these changes
👍

2024-08-15 06:50 UTC, merged