Add warning message on publication date
BIBSYSDEV/NVA-Frontend pull request #6030
Opened 2024-08-12 09:19 UTC by denektenina

# Description

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47315](https://sikt.atlassian.net/browse/NP-47315)

When user creates a new registration and writes a title, we do a search to see if the same title is already registered in NVA. If it is, we display a warning message under the input field.

In this task, we are adding a similar warning field under the publication date field, if the registration has both the same title AND the same registration date as another registration.

Earlier:

![image](https://github.com/user-attachments/assets/ce664e12-13a3-47c9-b406-756af77b75fb)

Now:

![image](https://github.com/user-attachments/assets/080b21a8-0d40-480b-9b8c-66a495cb42e5)

# Checklist

Ensure that the changes are aligned with the expectations of PO/designer before marking the PR as ready for review.

Also ensure that the following criterias are met:

- [ ] The changes are working as expected
- [ ] The changes are tested OK for different screen sizes
- [ ] The changes are tested OK for a11y
- [ ] Interactive elements have data-testids
- [ ] I have done a QA of my own changes

_Note: some of these criterias may not always be relevant, and can simply be marked as completed._

2024-08-12 11:04 UTC, elkebab requested changes
Syns egentlig det ble seende ganske bra ut jeg! Selv om jeg var litt skeptisk i utgangspunktet til det som var ønsket her 😅 
Eneste must-endring er egentlig `id`->`identifier` for min del av det jeg har kommentert på

2024-08-12 11:04 UTC, elkebab commented on src/pages/registration/DescriptionPanel.tsx
> +          id={duplicateRegistration!.identifier}
Siden alt dette forutsetter at man har en duplikat, er det kanskje naturlig å bare legge inn en eksplisitt sjekk på det først, og slipper unna litt `?`/`!` etterpå?
```suggestion
      {duplicateRegistration && registrationsHaveSamePublicationDate(
        duplicateRegistration.entityDescription?.publicationDate,
        values.entityDescription?.publicationDate
      ) && (
        <DuplicateWarning
          name={duplicateRegistration.entityDescription?.mainTitle}
          id={duplicateRegistration.identifier}
```

2024-08-12 11:27 UTC, denektenina commented on src/translations/nbTranslations.json
> +      "duplicate_publication_date_warning": "Den mulige duplikaten i NVA har også samme publikasjonsdato. Vennligst avbryt registreringen dersom det er det samme resultatet.",
Ja kanskje best å bruke det som står i tasken

2024-08-12 11:38 UTC, denektenina commented on src/utils/registration-helpers.ts
> +  return isSame;
Ja de kan være undefined eller tom streng, så jeg har en ekstra sjekk på at de er til stede før jeg sjekker dem.

2024-08-12 11:41 UTC, denektenina commented on src/pages/registration/DuplicateWarning.tsx
> +  name?: string;
Jo, vi viser advarselen, men ikke linken til duplikaten under

2024-08-13 07:05 UTC, elkebab approved these changes

2024-08-13 07:16 UTC, merged