Np 47279 k50 add cancel button in registration wizard v2
BIBSYSDEV/NVA-Frontend pull request #6113
Opened 2024-08-23 10:56 UTC by iBuzza

Reverts BIBSYSDEV/NVA-Frontend#6112

2024-11-05 10:30 UTC, iBuzza commented
Ikke så store endringer fra den orginale PR'en. Hovedsaklig fjernet state fra `StartEmptyRegistration`, `LinkRegistration` og `UploadRegistration`, da det var dette som skapte konflikt med "Lagre og se"-knappen.

2024-11-05 11:01 UTC, elkebab reviewed
Noen småting, ellers ser koden bra ut!
Har ikke testet enda, men skal gjøre det etter lunsj

2024-11-05 11:01 UTC, elkebab commented on src/utils/urlPaths.ts
> +export const getRegistrationWizardLink = (identifier: string, options: RegistrationWizardOptions = {}) => {
som nevnt i tidligere kommentar ser jeg ikke noen grunn til å ha både `getRegistrationWizardPath` og `getRegistrationWizardLink` (?)

2024-11-05 11:45 UTC, elkebab requested changes
Når man trykker "Lagre og se" skal man som standard se landing page, ikke gå tilbake til hvor man kom fra

https://github.com/user-attachments/assets/240d9cbb-38d6-42ce-af29-e5ccc56b13c1

2024-11-05 11:48 UTC, elkebab commented on src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
> +        history.push(getRegistrationWizardLink(registrationIdentifier));
Ah, ja det er kanskje behov for å bare lenke uten å sette den også ja 👍 Kan bli vanskelig å vite når man skal bruke hva da, men tror jeg skjønner grunnen til at det er der, og ser ikke noen bedre løsning selv heller sånn umiddelbart

2024-11-05 11:48 UTC, elkebab commented on src/utils/urlPaths.ts
> +export const getRegistrationWizardLink = (identifier: string, options: RegistrationWizardOptions = {}) => {
avklart her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6113#discussion_r1829207785

2024-11-06 07:56 UTC, elkebab submitted a review, later dismissed

2024-11-06 07:56 UTC, elkebab commented on src/pages/registration/RegistrationFormActions.tsx
> +      history.push(UrlPathTemplate.Home);
hadde det vært bedre å sende brukeren til Landing Page i stedet, sånn at man fortsatt er i kontekst av det resultatet? Vet ikke, bare en tanke som slo meg

2024-11-06 08:26 UTC, iBuzza commented on src/pages/registration/RegistrationFormActions.tsx
> +      history.push(UrlPathTemplate.Home);
Jo, enig i det! Skal fikse

2024-11-06 08:31 UTC, elkebab approved these changes

2024-11-06 13:51 UTC, merged