Create "New project" view
BIBSYSDEV/NVA-Frontend pull request #6139
Opened 2024-08-27 13:58 UTC by denektenina

# Description

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47283](https://sikt.atlassian.net/browse/NP-47283)

**⚠This is only visible when you have beta toggled to true in local storage ⚠**

You get to this view my going to Min Side --> "Prosjektregistreringer" in the left panel -> click "Nytt prosjekt"

This is a part of the effort to create a new create project-wizard [(NP-47281)](https://sikt.atlassian.net/browse/NP-47281), and there is a subtask for all the functionality to add.

In this PR we are adding the initial form for creating a new project:

**What should work after this PR:**
* You can start a new project, either through the NFR-view or the "Empty project"-view
* When you click the next button you should get into the normal edit-form with the values you pre-filled on the page before
* When you click save, the new project is created
* It is not possible to click save until all mandatory values are filled
* This new view should only be visible when beta is toggled to true in localStorage, so verify that it looks as before when this is not the case.
* You can cancel edit and will then return to where you came from

**Things that are not working and will be fixed in later PRs:**
* The stepper on top is not ready for mobile-view yet

# Checklist

Ensure that the changes are aligned with the expectations of PO/designer before marking the PR as ready for review.

Also ensure that the following criterias are met:

- [ ] The changes are working as expected
- [ ] The changes are tested OK for different screen sizes
- [ ] The changes are tested OK for a11y
- [ ] Interactive elements have data-testids
- [ ] I have done a QA of my own changes

_Note: some of these criterias may not always be relevant, and can simply be marked as completed._

2024-08-28 13:59 UTC, elkebab requested changes
Ser ut til å virke fint i praksis! Noen småting rundt opprydding og ting du kan ha i bakhodet

Mulig dette med fordel kunne vært delt opp i 2 PRs også, en å starte med tomt prosjekt, og en med NFR.
Hadde fort blitt litt mer jobb med rebasing/merging da, men hadde blitt raskere QA-feedback og slipper samme kommentar på 2 ting til gjengjeld

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/CreateProjectAccordion.tsx
> +            <Typography>{description}</Typography>
ser at `description` er optional, så for å unngå en potensielt tom `<p>`:
```suggestion
            {description && <Typography>{description}</Typography>}
```

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/CreateProjectAccordion.tsx
> +          <Box>
om den ikke skal ha noen videre styling e.l. liker jeg personlig best å droppe den ekstra importen av Box for MUI-ting som uansett ikke brukes
```suggestion
          <div>
```

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/EmptyProjectForm.tsx
> +  const [title, setTitle] = useState('');
liker at sånne enkle ting blir gjort sånn, og ikke wrappes i Formik som vi/jeg har hatt en tendens til å gjør mange plasser! Det fører bare til at man må sette seg inn i mer for å skjønne ganske enkel ting.

Vil man være purist kan man gjøre det meste med ren HTML også, og slippe rerender for hvert tastetrykk, ved å ha en `<form>` med `onSubmit` osv. Vi har noen eksempel i `NviCandidateRejectionDialog.tsx` og `ConfirmMessageDialog.tsx` om du er nysgjerrig

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/CreateProject.tsx
> +  const [showProjectForm, setShowProjectForm] = useState<boolean>(false);
Etter å ha sett i child components her, ser det kanskje ut som at denne er overflødig, og i praksis bare skal speile verdien til `newProject` 🤔 
```suggestion
  const showProjectForm = !!newProject;
```

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/EmptyProjectForm.tsx
> +      <Box sx={{ display: 'flex', flexDirection: 'column' }}>
Siden det ligger en flex her er det kanskje naturlig at den også styrer gaps i stedet for at det er i `mt` på knappen?
```suggestion
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
```

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/EmptyProjectForm.tsx
> +          </>
MUI Button har en prop for `startIcon` og `endIcon`, så vi slipper å passe på spacing og sånt selv
```suggestion
          data-testid={dataTestId.newProjectPage.startEmptyProjectButton}
          endIcon={<EastOutlinedIcon />}>
          {t('project.form.start_empty_project')}
```

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/NFRProject.tsx
En liten notis om man starter med NFR-prosjekt nå, er at navnet til prosjektleder ikke dukker opp som hjelp igjen når man skal registrere prosjektleder.
Ønsket (kravet?) var at man automatisk skulle få et søk på navnet som sto der, men lurer på om jeg kanskje kutta i svingen sånn at navnet bare ble vist når man legger til prosjektleder 🤔  Pass på at det er en oppgave på å implementere det om det ikke fins allerede hvertfall!

Fra gammel dialog:
![bilde](https://github.com/user-attachments/assets/020a0256-e8d6-41e2-a2ce-90288e74e5ef)

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/CreateProject.tsx
>  const CreateProject = () => {
```suggestion
export const CreateProject = () => {
```

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/NFRProject.tsx
> +          </>
```suggestion
          data-testid={dataTestId.newProjectPage.startNfrProjectButton}
          endIcon={<EastOutlinedIcon />}>
          {t('project.form.start_registering_project')}
```

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/NFRProject.tsx
> +      <Box sx={{ display: 'flex', flexDirection: 'column' }}>
samme som i `EmptyProjectForm`, tenker det hadde vært naturlig at container har gap heller enn at button har margin.
Om ikke container skal ha gap, kunne faktisk hele den `<Box>`en vært tatt vekk, og knappen kunne hatt `placeSelf: 'end'` for å få den til høyre

2024-08-28 13:59 UTC, elkebab commented on src/pages/project/project_wizard/NRFProjectOption.tsx
> +export const NFRProjectOption = ({ project }: NFRProjectOptionProps) => {
samme casing som ellers? gjelder filnavnet også
```suggestion
interface NfrProjectOptionProps {
  project: NfrProject;
}

export const NfrProjectOption = ({ project }: NfrProjectOptionProps) => {
```

2024-08-28 14:24 UTC, denektenina commented on src/api/hooks/useNfrProjectSearch.ts
> +  return useFetch<SearchResponse<NfrProject>>({
Hehe ja den skilte seg veldig ut fra de andre. Vet ikke om vi kan gjøre det på den andre måten nå? Jeg bare kopierte det vi hadde fra før, men laget det til en hook, og tenkte vi kan endre det om nødvendig en gang vi har tid.

2024-08-28 14:25 UTC, denektenina commented on src/components/styled/Wrappers.tsx
> +  flexDirection: 'row',
Ja kanskje greit å være eksplisitt akkurat her hvor det er delte, gjenbrukbare stiler? (Jeg er ganske glad i å gjøre det eksplisitt alltid)

2024-08-28 14:29 UTC, denektenina commented on src/pages/project/project_wizard/CreateProject.tsx
> +              coordinatingInstitution={currentInstitutionQuery.data ?? emptyProject.coordinatingInstitution}
Jeg her bare overfører jeg gammel funksjonalitet

2024-08-28 14:37 UTC, denektenina commented on src/pages/project/project_wizard/CreateProject.tsx
> +  const [showProjectForm, setShowProjectForm] = useState<boolean>(false);
Bra forslag! Jeg prøvde det og det funker ikke siden newProject aldri egentlig er tom (den starter med empty project), jeg kunne sjekket på tittel eller noe, men da begynner det å føles litt hacky. Dette er ganske clean, selv om det er litt overtydelig.

2024-08-28 14:43 UTC, denektenina commented on src/pages/project/project_wizard/NFRProject.tsx
Takk for tips! La til oppgave på det.

2024-08-28 14:51 UTC, denektenina commented on src/translations/nbTranslations.json
> +    "project": "Prosjekt",
Ja 😖

2024-08-28 14:52 UTC, denektenina commented on src/pages/project/project_wizard/ProjectForm.tsx
> +  const projectWithId = Object.prototype.hasOwnProperty.call(project, 'id') ? (project as CristinProject) : undefined;
Da bruker jeg den som er vanlig i prosjektet

2024-08-28 14:54 UTC, denektenina commented on src/pages/project/project_wizard/ProjectForm.tsx
> +  project: SaveCristinProject | CristinProject;
Ja jeg syns dette ble overraskende "enkelt" selv om jeg må sjekke på id her og der

2024-08-29 06:58 UTC, elkebab approved these changes

2024-08-29 07:18 UTC, merged