Added validation for Phd related results
BIBSYSDEV/NVA-Frontend pull request #6431
Opened 2024-10-17 12:24 UTC by iBuzza

2024-10-17 12:45 UTC, elkebab commented on src/pages/registration/resource_type_tab/sub_type_forms/degree_types/PhdForm.tsx
> +                    validate={(value: string) =>
Skulle ikke dette feltet blitt validert av modellen vi har i formik som alle andre typer?
Altså ved å legges til i `degreePublicationInstance` i `referenceValidation.ts`. Ellers blir det fort vanskelig å se hvor alle feilmeldinger trigges fra da

2024-10-17 12:46 UTC, elkebab commented on src/pages/registration/resource_type_tab/sub_type_forms/degree_types/PhdForm.tsx
> +                    validate={(value: string) =>
Usikker på om formik submit tar hensyn til sånne inline-valideringer ved submit også, eller om det bare er for visning til bruker 🤔

2024-10-22 09:27 UTC, elkebab commented on src/utils/validation/registration/referenceValidation.ts
> +    Yup.lazy((item) => (item.type === 'UnconfirmedDocument' ? unconfirmedDocumentSchema : confirmedDocumentSchema))
Har ikke vært borti lazy her før, så usikker på hvordan den virker i praksis.
Tidligere har vi mange `when()`-sjekker som sjekker bare når det gjelder for enkelte type. Denne skal vel valideres bare når `type = PhD`, så tenker det er en naturlig tilnærming?

2024-10-22 13:59 UTC, elkebab requested changes
2 ting jeg ser mangler etter en rask funksjonssjekk:
- Dette feltet valideres ikke når man går til en ny tab
- tab-validering tar ikke hensyn til dette feltet

![bilde](https://github.com/user-attachments/assets/a833cf9a-07c5-44bf-b424-f7d9581970b6)

2024-10-22 13:59 UTC, elkebab commented on src/utils/validation/registration/referenceValidation.ts
> +    .of(Yup.lazy((item) => (item.type === 'UnconfirmedDocument' ? unconfirmedDocumentSchema : confirmedDocumentSchema)))
noen bestemt grunn til at du bruker lazy her? Godt mulig det er best og at vi skulle hatt det andre plasser også, men vi har ikke brukt det noen plasser før og ser ikke at det skal være noe spesielt med dette feltet som krever noe asynkront 🤔

2024-10-22 13:59 UTC, elkebab commented on src/utils/validation/registration/referenceValidation.ts
> +      then: (schema) => schema.required(),
tenkte først det er naturlig å definere typen (som nå er på linje 321) her, sånn at det bare skjer når det faktisk er en PhD. Men `related` er sikkert samme uansett hvilken kategori det er, så mulig det er like greit å gjøre det slik

2024-10-22 13:59 UTC, elkebab commented on src/utils/validation/registration/referenceValidation.ts
> +  sequence: Yup.number().required(),
Hvordan kan denne være required når den ikke ser ut til å finnes? 🤔 
Sånn jeg leser det burde det aldri være lov å publisere med en ConfirmedDocument nå, siden dette feltet er required men vil mangle

```suggestion
```

![bilde](https://github.com/user-attachments/assets/fb7115e5-371c-40c7-8dd1-4ad32f93b2e2)

2024-10-22 14:01 UTC, elkebab commented on src/utils/validation/registration/referenceValidation.ts
> +  text: Yup.string().required(resourceErrorMessage.typeRequired),
Misvisende tekst
![bilde](https://github.com/user-attachments/assets/ae4c9670-aaf6-4c09-b589-9bbd8ccb7eb0)

2024-10-22 14:30 UTC, elkebab commented on src/utils/validation/registration/referenceValidation.ts
> +import { ContextPublisher, PublicationChannelType, UnconfirmedDocument } from '../../../types/registration.types';
brukes ikke?

```suggestion
import { ContextPublisher, PublicationChannelType } from '../../../types/registration.types';
```

2024-10-24 12:38 UTC, iBuzza commented on src/utils/formik-helpers/formik-helpers.ts
> +const getAllResourceFields = (publicationInstance: any) => {
Ble ikke rett med  `PublicationInstance`, så satt den tilbake til `any` igjen.

2024-10-24 13:31 UTC, elkebab commented on src/utils/validation/registration/referenceValidation.ts
> +  text: Yup.string().required(resourceErrorMessage.typeRequired),
"Tittel på relatert resultat" e.l. er kanskje det beste? Men ingen deal-breaker for meg om det blir bare "Tittel". Kanskje Mayli har noen meninger også om du ikke har hørt der

2024-10-24 13:37 UTC, elkebab commented on src/utils/formik-helpers/formik-helpers.ts
> +      const publicationInstance = registration.entityDescription?.reference
greit å gi eksplisitt navn, så man ikke ser feil når `publicationInstance` nevnes så mange ganger nedover her
```suggestion
      const degreePublicationInstance = registration.entityDescription?.reference
```

2024-10-25 08:32 UTC, elkebab submitted a review, later dismissed
Ikke testet nå etter siste endringer, men koden ser bra ut!
Kan vurdere selv hva du vil gjøre med tekst for feilmeldingen

2024-10-25 08:36 UTC, elkebab approved these changes

2024-10-25 09:21 UTC, merged