Np 47714 change order of related results on phd
BIBSYSDEV/NVA-Frontend pull request #6458
Opened 2024-10-23 07:02 UTC by iBuzza

# Description

Link to Jira issue: TODO

[TODO: Describe what this PR solves]

# Checklist

Ensure that the changes are aligned with the expectations of PO/designer before marking the PR as ready for review.

Also ensure that the following criterias are met:

- [ ] The changes are working as expected
- [ ] The changes are tested OK for different screen sizes
- [ ] The changes are tested OK for a11y
- [ ] Interactive elements have data-testids
- [ ] I have done a QA of my own changes

_Note: some of these criterias may not always be relevant, and can simply be marked as completed._

2024-10-31 09:07 UTC, elkebab requested changes
Starter med en rask review basert på funksjonalitet nå, så ser jeg på koden senere, når det funksjonelle er på plass.

Generelt tror jeg vi kunne forenklet en del her da, så vi skulle nok vært bedre på å diskutere mulige løsninger underveis. Min første tanke var at vi bare skulle flytte elementet i arrayet, så kunne vi gått gjennom hele arrayet og sørga for at alle sequence-verdier stemmer med plassering i arrayet. Ikke sikkert det hadde vært bedre altså, men tror det hadde tatt vekk ganske mye kode (og mye manuell håndtering av indekser), i tillegg til at vi hadde sikret at arrayet blir i riktig rekkefølge også (som på contributors bl.a.)

2024-10-31 14:51 UTC, elkebab commented on src/pages/public_registration/public_links/ShowRelatedDocuments.tsx
noen ting her:

1. `key` er satt på en underkomponent, sånn at det blir feil (vises også i konsollen)
![bilde](https://github.com/user-attachments/assets/a28393d8-4bf7-4c8d-885f-e96827a72433)

2. Det mappes gjennom et array, hvor hver `UnconfirmedDocument` lager hver sin egen liste med bare ett element. Mens fritekstinnslag kommer uten noen <li>, <p>, e.l. Dette gir ganske rar HTML. Lista burde være wrappet rundt alt
![bilde](https://github.com/user-attachments/assets/78fa82a3-dc90-4319-95cd-3275afeaa8d9)

Grov skisse:
```
if (related.length === 0) {
  return null;
}

return (
  <List>
    {related.sort().map((document, index) => (
      <ListItem>
        {document.type === 'ConfirmedDocument' ? (
          <ShowRelatedRegistrationUris />
        ) : (
          <Typography>{document.text}</Typography>
        )}
      </ListItem>
    ))}
  </List>
);
```

2024-10-31 14:56 UTC, elkebab commented on src/pages/registration/resource_type_tab/components/SearchRelatedResultField.tsx
> +                  sequence: related ? related?.length + 1 : null,
```suggestion
                  sequence: related ? related.length + 1 : null,
```

2024-11-04 08:54 UTC, elkebab requested changes
Noen overflødige tags og kode etc

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
> +    const newIndex =
Dette virker ganske komplisert og innviklet når problemet bare er å bytte plassering av to elementer. Går man for en trippel ternary burde man ha en god grunn, da det er ekkelt å gjøre endringer/bugfikser her senere. Alle artistiske resultat har lignende sortering, og der er det bare løst med en one-liner med `move()` fra formik  (se feks `ArtisticMusicPerformanceForm.tsx`). I tilfelle her måtte vi kanskje i tillegg satt `sequence` da, men det er en enkel iterasjon etter elementet er riktig plassert.
Ikke sikkert vi bør bruke mer tid på det nå da, men husk til senere å stille spørsmål til hvorfor man gjør det man gjør, og om det kan forenkles :)

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
> +
```suggestion
  const moveRelatedResult = (newSequence: number, oldSequence: number) => {
```

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
> +        components={[
Fin løsning! 👍

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
> +            onClick={() => push(createEmptyUnconfirmedDocument(related.length + 1))}
personlig liker jeg nok best når dette er eksplisitt, da jeg ikke kan vite at arumentet der settes til sequence uten å sjekke `createEmptyUnconfirmedDocument`. Men det er vel en ren subjektiv sak, så kan godt være sånn også :)
```suggestion
            onClick={() => push({
               ...emptyUnconfirmedDocument, 
               sequence: related.length + 1,
             })}
```

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
> +            ?.sort((a, b) => (a.sequence && b.sequence ? a.sequence - b.sequence : 0))
```suggestion
            .sort((a, b) => (a.sequence && b.sequence ? a.sequence - b.sequence : 0))
```

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
> +            })}
kan spare oss for ett overflødig innrykk
```suggestion
            .map((document, index) => (
              <RelatedResultItem
                key={index}
                document={document}
                index={index}
                relatedLength={related.length}
                onMoveRelatedResult={moveRelatedResult}
                onRemoveDocument={removeRelatedItem}
              />
            ))}
```

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/RelatedResultItem.tsx
> +            </div>
Kunne ev. angitt `gridColumn` e.l. her også, i stedet for å legg inn tomme divs
```suggestion
              {document.sequence !== relatedLength && (
                <Tooltip title={t('common.move_down')}>
                  <IconButton
                    size="small"
                    sx={{ minWidth: 'auto', height: 'fit-content', gridColumn: 1 }}
                    onClick={() =>
                      !!document.sequence && document.sequence > 0
                        ? onMoveRelatedResult(document.sequence + 1, document.sequence)
                        : null
                    }>
                    <ArrowDownwardIcon color="primary" />
                  </IconButton>
                </Tooltip>
              )}
              {document.sequence !== 1 && (
                <Tooltip title={t('common.move_up')}>
                  <IconButton
                    size="small"
                    sx={{ minWidth: 'auto', height: 'fit-content', gridColumn: 2 }}
                    onClick={() =>
                      !!document.sequence && document.sequence > 0
                        ? onMoveRelatedResult(document.sequence - 1, document.sequence)
                        : null
                    }>
                    <ArrowUpwardIcon color="primary" />
                  </IconButton>
                </Tooltip>
              )}
```

2024-11-04 08:54 UTC, elkebab commented on src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/RelatedResultItem.tsx
> +          }}>
flex-boks med bare ett element burde ikke være nødvendig?
```suggestion
```

2024-11-04 09:23 UTC, iBuzza commented on src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
> +            onClick={() => push(createEmptyUnconfirmedDocument(related.length + 1))}
Enig der👍

2024-11-04 11:09 UTC, elkebab approved these changes

2024-11-04 11:15 UTC, merged